In [6]:
import json
import pandas as pd

actor_name_map = {}
actor_genre_map = {}


with open("imdb_movies_2000to2022.prolific.json", "r") as in_file:
    for line in in_file:
        this_movie = json.loads(line)

        for actor_id,actor_name in this_movie['actors']:
            actor_name_map[actor_id] = actor_name
            this_actors_genre = actor_genre_map.get(actor_id, {})
            
            for genre in this_movie["genres"]:
              this_actors_genre[genre] = this_actors_genre.get(genre, 0) + 1
            
            actor_genre_map[actor_id] = this_actors_genre

actor_genre_map["nm1165110"]


index = actor_genre_map.keys()
data = [actor_genre_map[k] for k in index]
df = pd.DataFrame(data, index=index)

df = df.fillna(0, inplace=True)
df

,Comedy,Fantasy,Romance,Drama,Mystery,Thriller,Action,Biography,Crime,War,...,Horror,Documentary,Sport,News,Family,Music,,Western,Short,Reality-TV
nm0000212,7.0,1.0,6.0,6.0,1.0,2.0,1.0,1.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm0413168,7.0,3.0,5.0,12.0,5.0,2.0,14.0,4.0,6.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm0000630,8.0,2.0,6.0,14.0,2.0,3.0,4.0,5.0,1.0,1.0,...,3.0,7.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
nm0005227,10.0,1.0,2.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
nm0864851,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
nm9504284,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm10592896,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm7216750,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm0936300,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm10375007,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [57]:
query_id = "nm1165110"
query_vector = df.loc[[query_id]]

from sklearn.metrics import DistanceMetric
dist = DistanceMetric.get_metric('euclidean')

distances = dist.pairwise(query_vector, df)[0]
distance_series = pd.Series(distances, index = df.index)

print("###EUCLIDEAN WITHOUT NORMALIZATION")
print("="*32)

top_10_ids = distance_series.drop(index=query_id).nsmallest(10)
for actor_id in top_10_ids.index:
  print(f"{actor_name_map[actor_id]} ({actor_id}): {top_10_ids[actor_id]:.4f}")

#EUCLIDEAN WITHOUT NORM

###EUCLIDEAN WITHOUT NORMALIZATION
================================
Tom Cruise (nm0000129): 5.4772
Henry Cavill (nm0147147): 8.2462
Tyrese Gibson (nm0879085): 8.8318
Orlando Bloom (nm0089217): 9.0554
Vin Diesel (nm0004874): 9.2195
Angelina Jolie (nm0001401): 9.2195
Adrian Paul (nm0001600): 9.5917
Jet Li (nm0001472): 9.5917
Mark Dacascos (nm0001092): 9.7980
Lorenzo Lamas (nm0001444): 10.0499

In [58]:
query_id = "nm1165110"
query_vector = df_norm.loc[[query_id]]

from sklearn.metrics import DistanceMetric
dist = DistanceMetric.get_metric('euclidean')

distances = dist.pairwise(query_vector, df_norm)[0]
distance_series = pd.Series(distances, index = df_norm.index)

print("###EUCLIDEAN WITH NORMALIZATION")
print("="*32)

top_10_ids = distance_series.drop(index=query_id).nsmallest(10)
for actor_id in top_10_ids.index:
  print(f"{actor_name_map[actor_id]} ({actor_id}): {top_10_ids[actor_id]:.4f}")

#EUCLIDEAN WITH NORMALIZATION

###EUCLIDEAN WITH NORMALIZATION
================================
Tom Cruise (nm0000129): 0.0979
Ray Stevenson (nm0829032): 0.1250
Henry Cavill (nm0147147): 0.1280
Tiger Shroff (nm5899377): 0.1345
Jordi Mollà (nm0003244): 0.1347
Sudeep (nm1679372): 0.1360
Taylor Kitsch (nm2018237): 0.1405
Tom Holland (nm4043618): 0.1424
Scott Eastwood (nm2207222): 0.1495
Vaani Kapoor (nm5744729): 0.1544

In [35]:
df.sum(axis=0)

Comedy         24943.0
Fantasy         3630.0
Romance        10240.0
Drama          41785.0
Mystery         6175.0
Thriller       16475.0
Action         15609.0
Biography       3088.0
Crime          11195.0
War              910.0
Adventure       6780.0
Sci-Fi          4478.0
Animation       2532.0
Musical          702.0
History         1531.0
Horror         13051.0
Documentary     1651.0
Sport           1862.0
News              40.0
Family          3958.0
Music           1544.0
                 643.0
Western          833.0
Short              4.0
Reality-TV         6.0
dtype: float64

In [36]:
df_norm = df.divide(df.sum(axis=1), axis=0)
df_norm.sum(axis=1)

nm0000212     1.0
nm0413168     1.0
nm0000630     1.0
nm0005227     1.0
nm0864851     1.0
             ...
nm9504284     1.0
nm10592896    1.0
nm7216750     1.0
nm0936300     1.0
nm10375007    1.0
Length: 33609, dtype: float64

In [40]:
query_vector

,Comedy,Fantasy,Romance,Drama,Mystery,Thriller,Action,Biography,Crime,War,...,Horror,Documentary,Sport,News,Family,Music,,Western,Short,Reality-TV
nm1165110,3.0,2.0,0.0,7.0,1.0,4.0,17.0,2.0,3.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [53]:
from sklearn.metrics.pairwise import cosine_distances

query_id = "nm1165110"
query_vector = df.loc[[query_id]]

distances = cosine_distances(query_vector, df)[0]
distance_series = pd.Series(distances, index=df.index)

print("###COSINE WITHOUT NORMALIZATION")
print("="*32)

top_10_ids = distance_series.drop(index=query_id).nsmallest(10)
for actor_id in top_10_ids.index:
  print(f"{actor_name_map[actor_id]} ({actor_id}): {top_10_ids[actor_id]:.4f}")

###COSINE WITHOUT NORMALIZATION
================================
Tom Cruise (nm0000129): 0.0269
Henry Cavill (nm0147147): 0.0446
Ray Stevenson (nm0829032): 0.0452
Tiger Shroff (nm5899377): 0.0488
Sudeep (nm1679372): 0.0517
Jordi Mollà (nm0003244): 0.0534
Richard Norton (nm0636280): 0.0565
Mark Mortimer (nm0607884): 0.0565
Taylor Kitsch (nm2018237): 0.0580
Tom Holland (nm4043618): 0.0602

In [56]:
from sklearn.metrics.pairwise import cosine_distances

query_id = "nm1165110"
query_vector = df_norm.loc[[query_id]]

distances = cosine_distances(query_vector, df_norm)[0]
distance_series = pd.Series(distances, index=df_norm.index)

print("###COSINE WITH NORMALIZATION")
print("="*32)

top_10_ids = distance_series.drop(index=query_id).nsmallest(10)
for actor_id in top_10_ids.index:
  print(f"{actor_name_map[actor_id]} ({actor_id}): {top_10_ids[actor_id]:.4f}")

###COSINE WITH NORMALIZATION
================================
Tom Cruise (nm0000129): 0.0269
Henry Cavill (nm0147147): 0.0446
Ray Stevenson (nm0829032): 0.0452
Tiger Shroff (nm5899377): 0.0488
Sudeep (nm1679372): 0.0517
Jordi Mollà (nm0003244): 0.0534
Richard Norton (nm0636280): 0.0565
Mark Mortimer (nm0607884): 0.0565
Taylor Kitsch (nm2018237): 0.0580
Tom Holland (nm4043618): 0.0602